#!/usr/bin/env python

import os.path
import subprocess
import sys
import argparse
import datetime

THIS_DIR = os.path.dirname(os.path.abspath(__file__))

def color_print(str):
  color_begin = '\033[33m'
  color_end = '\033[0m'
  print color_begin + str + color_end

def run(config):
  for index, name_and_command in enumerate(config):
    index += 1
    name = name_and_command['name']
    command = name_and_command['command']
    color_print('ACTION %d: %s' %(index, name))
    color_print('=' * 50)
    return_code = subprocess.call(command)
    if return_code != 0:
      color_print('ACTION %d FAILED: %s' % (index, name))
      return

def main():
  description = ''' intrude a dylib libary to a ipa package.

  {self_name} --ipa /path/to/some.ipa --dylib /path/to/executable/some.dylib'''.format(self_name=sys.argv[0])
  

  parser = argparse.ArgumentParser(description=description, formatter_class=argparse.RawDescriptionHelpFormatter,)
  parser.add_argument('--ipa', action='store', dest='ipa', required=True, help='full path for ipa file')
  parser.add_argument('--dylib', action='store', dest='dylib', required=True, help='full path for dylib library')
  parser.add_argument('--dry_run', action='store_true', help='dry run, only show the action command line')
  args = parser.parse_args()

if __name__ == '__main__':
  main()

# vim: number list tabstop=2 shiftwidth=2 expandtab
